version: 3.8,
services:
  dev-db:
    image: postgres
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432
    networks:
      - freecodecamp
networks:
  freecodecamp:   
